version: "2"

services:
    db:
        image: mysql:5.7
        volumes:
            - .mysql_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"

    redis:
        image: redis:3.2.9
        volumes:
            - ".redis_data:/data"
        ports:
            - "6379:6379"
        command: redis-server --appendonly yes --requirepass foobared

    web:
        build: .
        command: bundle exec rails s -p 3000 -b "0.0.0.0"
        volumes:
            - .:/myapp
        ports:
            - "3000:3000"
        links:
            - db
            - redis